import React from 'react';
declare const mitochondrialVariantTableColumns: ({
    key: string;
    heading: string;
    tooltip: string;
    grow: number;
    minWidth: number;
    compareFunction: (v1: any, v2: any, order?: string) => any;
    render: (row: any, key: any) => React.JSX.Element;
    description?: undefined;
    getSearchTerms?: undefined;
    descriptionInContext?: undefined;
    contextNotes?: undefined;
    shouldShowInContext?: undefined;
    isRowHeader?: undefined;
} | {
    key: string;
    heading: string;
    description: string;
    grow: number;
    minWidth: number;
    compareFunction: (v1: any, v2: any, order?: string) => any;
    getSearchTerms: (variant: any) => any[];
    render: (variant: any, _: any, { highlightWords }: any) => React.JSX.Element;
    tooltip?: undefined;
    descriptionInContext?: undefined;
    contextNotes?: undefined;
    shouldShowInContext?: undefined;
    isRowHeader?: undefined;
} | {
    key: string;
    heading: string;
    description: string;
    descriptionInContext: (context: any, contextType: any) => string;
    grow: number;
    minWidth: number;
    compareFunction: (v1: any, v2: any, order?: string) => any;
    getSearchTerms: (variant: any) => any[];
    render: (row: any, key: any, { highlightWords }: any) => React.JSX.Element;
    tooltip?: undefined;
    contextNotes?: undefined;
    shouldShowInContext?: undefined;
    isRowHeader?: undefined;
} | {
    key: string;
    heading: string;
    description: string;
    grow: number;
    minWidth: number;
    compareFunction: (v1: any, v2: any, order?: string) => any;
    render: (row: any, key: any) => any;
    tooltip?: undefined;
    getSearchTerms?: undefined;
    descriptionInContext?: undefined;
    contextNotes?: undefined;
    shouldShowInContext?: undefined;
    isRowHeader?: undefined;
} | {
    key: string;
    heading: string;
    description: string;
    contextNotes: string;
    minWidth: number;
    render: (row: any) => React.JSX.Element;
    shouldShowInContext: (context: any, contextType: any) => boolean;
    tooltip?: undefined;
    grow?: undefined;
    compareFunction?: undefined;
    getSearchTerms?: undefined;
    descriptionInContext?: undefined;
    isRowHeader?: undefined;
} | {
    key: string;
    heading: string;
    description: string;
    grow: number;
    minWidth: number;
    render: (variant: any) => React.JSX.Element;
    tooltip?: undefined;
    compareFunction?: undefined;
    getSearchTerms?: undefined;
    descriptionInContext?: undefined;
    contextNotes?: undefined;
    shouldShowInContext?: undefined;
    isRowHeader?: undefined;
} | {
    key: string;
    heading: string;
    description: string;
    grow: number;
    isRowHeader: boolean;
    minWidth: number;
    compareFunction: (v1: any, v2: any, order?: string) => any;
    getSearchTerms: (variant: any) => any[];
    render: (variant: any, key: any, { highlightWords }: any) => React.JSX.Element;
    tooltip?: undefined;
    descriptionInContext?: undefined;
    contextNotes?: undefined;
    shouldShowInContext?: undefined;
})[];
export default mitochondrialVariantTableColumns;
export declare const getColumnsForContext: (context: any) => {};
