"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const react_1 = __importDefault(require("react"));
const styled_components_1 = __importDefault(require("styled-components"));
const ui_1 = require("@gnomad/ui");
const DocumentTitle_1 = __importDefault(require("./DocumentTitle"));
const InfoPage_1 = __importDefault(require("./InfoPage"));
const Citation = styled_components_1.default.cite `
  font-style: normal;
  line-height: 1.4;
`;
exports.default = () => (react_1.default.createElement(InfoPage_1.default, null,
    react_1.default.createElement(DocumentTitle_1.default, { title: "Publications" }),
    react_1.default.createElement(ui_1.PageHeading, null, "Publications"),
    react_1.default.createElement("p", null, "This page lists publications from the gnomAD group."),
    react_1.default.createElement("p", null, "If you want to cite gnomAD in a publication, please use the current flagship paper (except if referring to a previous version; see below). If you build online resources that include the data set, we ask that you provide links to the browser from the resource where relevant."),
    react_1.default.createElement("p", null, "There is no need to include us as authors on your manuscript, unless we contributed specific advice or analysis for your work."),
    react_1.default.createElement("p", null,
        "Current flagship paper (",
        react_1.default.createElement("b", null, "v3"),
        "):",
        react_1.default.createElement(ui_1.List, null,
            react_1.default.createElement(ui_1.ListItem, null,
                react_1.default.createElement(Citation, null,
                    "Chen, S.*, Francioli, L. C.*, Goodrich, J. K., Collins, R. L., Kanai, M., Wang, Q., Alf\u00F6ldi, J., Watts, N. A., Vittal, C., Gauthier, L. D., Poterba, T., Wilson, M. W., Tarasova, Y., Phu, W., Grant, R., Yohannes, M. T., Koenig, Z., Farjoun, Y., Banks, E., Donnelly, S., Gabriel, S., Gupta, N., Ferriera, S., Tolonen, C., Novod, S., Bergelson, L., Roazen, D., Ruano-Rubio, V., Covarrubias, M., Llanwarne, C., Petrillo, N., Wade, G., Jeandet, T., Munshi, R., Tibbetts, K., Genome Aggregation Database (gnomAD) Consortium, O\u2019Donnell-Luria, A., Solomonson, M., Seed, C., Martin, A. R., Talkowski, M. E., Rehm, H. L., Daly, M. J., Tiao, G., Neale, B. M.\u2020, MacArthur, D. G.\u2020 & Karczewski, K. J. A genomic mutational constraint map using variation in 76,156 human genomes",
                    ' ',
                    react_1.default.createElement("em", null, "Nature"),
                    " 625, 92\u2013100 (2024). ",
                    react_1.default.createElement(ui_1.ExternalLink, { href: "https://doi.org/10.1038/s41586-023-06045-0" }, "https://doi.org/10.1038/s41586-023-06045-0"),
                    ' ',
                    react_1.default.createElement(ui_1.ExternalLink, { href: "https://citation-needed.springer.com/v2/references/10.1038/s41586-023-06045-0?format=refman&flavour=citation" }, "Download citation"))),
            "* contributed equally",
            react_1.default.createElement("br", null),
            "\u2020 contributed equally")),
    ' ',
    react_1.default.createElement("p", null,
        "Previous flagship papers:",
        react_1.default.createElement(ui_1.List, null,
            react_1.default.createElement(ui_1.ListItem, null,
                react_1.default.createElement("b", null, "v2"),
                ":",
                ' ',
                react_1.default.createElement(Citation, null,
                    "Karczewski, K. J., Francioli, L. C., Tiao, G., Cummings, B. B., Alf\u00F6ldi, J., Wang, Q., Collins, R. L., Laricchia, K. M., Ganna, A., Birnbaum, D. P., Gauthier, L. D., Brand, H., Solomonson, M., Watts, N. A., Rhodes, D., Singer-Berk, M., England, E. M., Seaby, E. G., Kosmicki, J. A., \u2026 MacArthur, D. G. The mutational constraint spectrum quantified from variation in 141,456 humans. ",
                    react_1.default.createElement("em", null, "Nature"),
                    " 581, 434\u2013443 (2020).",
                    ' ',
                    react_1.default.createElement(ui_1.ExternalLink, { href: "https://doi.org/10.1038/s41586-020-2308-7" }, "https://doi.org/10.1038/s41586-020-2308-7"),
                    ' ',
                    react_1.default.createElement(ui_1.ExternalLink, { href: "https://citation-needed.springer.com/v2/references/10.1038/s41586-020-2308-7?format=refman&flavour=citation" }, "Download citation"))),
            react_1.default.createElement(ui_1.ListItem, null,
                react_1.default.createElement("b", null, "ExAC"),
                ":",
                ' ',
                react_1.default.createElement(Citation, null,
                    "Lek, M., Karczewski, K. J.*, Minikel, E. V.*, Samocha, K. E.*, Banks, E., Fennell, T., O\u2019Donnell-Luria, A. H., Ware, J. S., Hill, A. J., Cummings, B. B., Tukiainen, T., Birnbaum, D. P., Kosmicki, J. A., Duncan, L. E., Estrada, K., Zhao, F., Zou, J., Pierce-Hoffman, E., \u2026 Daly, M. J., MacArthur, D. G. & Exome Aggregation Consortium. Analysis of protein-coding genetic variation in 60,706 humans. ",
                    react_1.default.createElement("em", null, "Nature"),
                    " 536, 285\u2013291 (2016). ",
                    react_1.default.createElement(ui_1.ExternalLink, { href: "https://doi.org/10.1038/nature19057" }, "https://doi.org/10.1038/nature19057"),
                    ' ',
                    react_1.default.createElement(ui_1.ExternalLink, { href: "https://citation-needed.springer.com/v2/references/10.1038/nature19057?format=refman&flavour=citation" }, "Download citation"))),
            "* contributed equally")),
    react_1.default.createElement("p", null,
        "Remaining publications:",
        react_1.default.createElement(ui_1.List, null,
            react_1.default.createElement(ui_1.ListItem, null,
                react_1.default.createElement(Citation, null,
                    "Guo, M. H.\u2020, Francioli, L. C.\u2020, Stenton, S. L., Goodrich, J. K., Watts, N. A., Singer-Berk, M., Groopman, E., Darnowsky, P. W., Solomonson, M., Baxter, S., gnomAD Project Consortium, Tiao, G., Neale, B. M., Hirschhorn, J. N., Rehm, H., Daly, M. J., O\u2019Donnell-Luria, A., Karczewski, K., MacArthur, D. G., Samocha, K. E. Inferring compound heterozygosity from large-scale exome sequencing data. ",
                    react_1.default.createElement("em", null, "Nature Genetics"),
                    " (2023).",
                    ' ',
                    react_1.default.createElement(ui_1.ExternalLink, { href: "https://doi.org/10.1038/s41588-023-01608-3" }, "https://doi.org/10.1038/s41588-023-01608-3"))),
            react_1.default.createElement(ui_1.ListItem, null,
                react_1.default.createElement(Citation, null,
                    "Gudmundsson, S., Singer-Berk, M., Watts, N. A., Phu, W., Goodrich, J. K., Solomonson, M., Genome Aggregation Database (gnomAD) Consortium, Rehm, H. L., MacArthur, D. G., O\u2019Donnell-Luria, A. Variant interpretation using population databases: Lessons from gnomAD. ",
                    react_1.default.createElement("em", null, "Human Mutation"),
                    " 1-19 (2021). ",
                    react_1.default.createElement(ui_1.ExternalLink, { href: "https://doi.org/10.1002/humu.24309" }, "https://doi.org/10.1002/humu.24309"))),
            react_1.default.createElement(ui_1.ListItem, null,
                react_1.default.createElement(Citation, null,
                    "Laricchia, K. M.*, Lake, N. J.*, Watts, N. A., Shand, M., Haessly, A., Gauthier, L. D., Benjamin, D., Banks, E., Soto, J., Garimella, K., Emery, J., Genome Aggregation Database (gnomAD) Consortium, Rehm, H. L., MacArthur, D. G., Tiao, G.\u2020, Lek, M.\u2020, Mootha, V. K.\u2020, Calvo, S. E.\u2020 Mitochondrial DNA variation across 56,434 individuals in gnomAD.",
                    ' ',
                    react_1.default.createElement("em", null, "Genome Res."),
                    " 32, 569\u2013582 (2022). ",
                    react_1.default.createElement(ui_1.ExternalLink, { href: "https://doi.org/10.1101/gr.276013.121" }, "https://doi.org/10.1101/gr.276013.121"))),
            react_1.default.createElement(ui_1.ListItem, null,
                react_1.default.createElement(Citation, null,
                    "Collins, R. L.*, Brand, H.*, Karczewski, K. J., Zhao, X., Alf\u00F6ldi, J., Francioli, L. C., Khera, A. V., Lowther, C., Gauthier, L. D., Wang, H., Watts, N. A., Solomonson, M., O\u2019Donnell-Luria, A., Baumann, A., Munshi, R., Walker, M., Whelan, C., Huang, Y., Brookings, T., \u2026 Talkowski, M. E. A structural variation reference for medical and population genetics. ",
                    react_1.default.createElement("em", null, "Nature"),
                    " 581, 444\u2013451 (2020). ",
                    react_1.default.createElement(ui_1.ExternalLink, { href: "https://doi.org/10.1038/s41586-020-2287-8" }, "https://doi.org/10.1038/s41586-020-2287-8"))),
            react_1.default.createElement(ui_1.ListItem, null,
                react_1.default.createElement(Citation, null,
                    "Cummings, B. B., Karczewski, K. J., Kosmicki, J. A., Seaby, E. G., Watts, N. A., Singer-Berk, M., Mudge, J. M., Karjalainen, J., Kyle Satterstrom, F., O\u2019Donnell-Luria, A., Poterba, T., Seed, C., Solomonson, M., Alf\u00F6ldi, J., The Genome Aggregation Database Production Team, The Genome Aggregation Database Consortium, Daly, M. J., & MacArthur, D. G. Transcript expression-aware annotation improves rare variant interpretation.",
                    ' ',
                    react_1.default.createElement("em", null, "Nature"),
                    " 581, 452\u2013458 (2020). ",
                    react_1.default.createElement(ui_1.ExternalLink, { href: "https://doi.org/10.1038/s41586-020-2329-2" }, "https://doi.org/10.1038/s41586-020-2329-2"))),
            react_1.default.createElement(ui_1.ListItem, null,
                react_1.default.createElement(Citation, null,
                    "Minikel, E. V., Karczewski, K. J., Martin, H. C., Cummings, B. B., Whiffin, N., Rhodes, D., Alf\u00F6ldi, J., Trembath, R. C., van Heel, D. A., Daly, M. J., Genome Aggregation Database Production Team, Genome Aggregation Database Consortium, Schreiber, S. L., & MacArthur, D. G. Evaluating potential drug targets through human loss-of-function genetic variation. ",
                    react_1.default.createElement("em", null, "Nature"),
                    " 581, 459\u2013464 (2020). ",
                    react_1.default.createElement(ui_1.ExternalLink, { href: "https://doi.org/10.1038/s41586-020-2267-z" }, "https://doi.org/10.1038/s41586-020-2267-z"))),
            react_1.default.createElement(ui_1.ListItem, null,
                react_1.default.createElement(Citation, null,
                    "Wang, Q., Pierce-Hoffman, E., Cummings, B. B., Karczewski, K. J., Alf\u00F6ldi, J., Francioli, L. C., Gauthier, L. D., Hill, A. J., O\u2019Donnell-Luria, A. H., Genome Aggregation Database (gnomAD) Production Team, Genome Aggregation Database (gnomAD) Consortium, & MacArthur, D. G. Landscape of multi-nucleotide variants in 125,748 human exomes and 15,708 genomes. ",
                    react_1.default.createElement("em", null, "Nature Communications"),
                    " 11, 2539 (2020).",
                    ' ',
                    react_1.default.createElement(ui_1.ExternalLink, { href: "https://doi.org/10.1038/s41467-019-12438-5" }, "https://doi.org/10.1038/s41467-019-12438-5"))),
            react_1.default.createElement(ui_1.ListItem, null,
                react_1.default.createElement(Citation, null,
                    "Whiffin, N.*, Armean, I. M.*, Kleinman, A.*, Marshall, J. L., Minikel, E. V., Goodrich, J. K., Quaife, N. M., Cole, J. B., Wang, Q., Karczewski, K. J., Cummings, B. B., Francioli, L., Laricchia, K., Guan, A., Alipanahi, B., Morrison, P., Baptista, M. A. S., Merchant, K. M., Genome Aggregation Database Production Team, \u2026 Cannon, P.\u2020, MacArthur, D. G.\u2020 The effect of LRRK2 loss-of-function variants in humans. ",
                    react_1.default.createElement("em", null, "Nature Medicine"),
                    ' ',
                    "(2020). ",
                    react_1.default.createElement(ui_1.ExternalLink, { href: "https://doi.org/10.1038/s41591-020-0893-5" }, "https://doi.org/10.1038/s41591-020-0893-5"))),
            react_1.default.createElement(ui_1.ListItem, null,
                react_1.default.createElement(Citation, null,
                    "Whiffin, N., Karczewski, K. J., Zhang, X., Chothani, S., Smith, M. J., Gareth Evans, D., Roberts, A. M., Quaife, N. M., Schafer, S., Rackham, O., Alf\u00F6ldi, J., O\u2019Donnell-Luria, A. H., Francioli, L. C., Genome Aggregation Database (gnomAD) Production Team, Genome Aggregation Database (gnomAD) Consortium, Cook, S. A., Barton, P. J. R., MacArthur, D. G.\u2020, & Ware, J. S.\u2020 Characterising the loss-of-function impact of 5\u2019 untranslated region variants in 15,708 individuals. ",
                    react_1.default.createElement("em", null, "Nature Communications"),
                    " 11, 2523 (2020).",
                    ' ',
                    react_1.default.createElement(ui_1.ExternalLink, { href: "https://doi.org/10.1038/s41467-019-10717-9" }, "https://doi.org/10.1038/s41467-019-10717-9"))),
            react_1.default.createElement(ui_1.ListItem, null,
                react_1.default.createElement(Citation, null,
                    "Karczewski, K. J., Gauthier, L. D., & Daly, M. J. Technical artifact drives apparent deviation from Hardy-Weinberg equilibrium at CCR5-\u220632 and other variants in gnomAD",
                    ' ',
                    react_1.default.createElement("em", null, "bioRxiv"),
                    " (p. 784157). ",
                    react_1.default.createElement(ui_1.ExternalLink, { href: "https://doi.org/10.1101/784157" }, "https://doi.org/10.1101/784157"))),
            react_1.default.createElement(ui_1.ListItem, null,
                react_1.default.createElement(Citation, null,
                    "Karczewski, K. J., Weisburd, B., Thomas, B., Solomonson, M., Ruderfer, D. M., Kavanagh, D., Hamamsy, T., Lek, M., Samocha, K. E., Cummings, B. B., Birnbaum, D., The Exome Aggregation Consortium, Daly, M. J., MacArthur, D. G.. The ExAC browser: displaying reference data information from over 60000 exomes. ",
                    react_1.default.createElement("em", null, "Nucleic Acids Research"),
                    ", Volume 45, Issue D1, January 2017, Pages D840\u2013D845, ",
                    react_1.default.createElement(ui_1.ExternalLink, { href: "https://doi.org/10.1093/nar/gkw971" }, "https://doi.org/10.1093/nar/gkw971"))),
            "* contributed equally",
            react_1.default.createElement("br", null),
            "\u2020 contributed equally"))));
//# sourceMappingURL=PublicationsPage.js.map