"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const react_1 = __importDefault(require("react"));
const DownloadFigure_1 = require("../DownloadFigure");
const TableStyles_1 = require("./TableStyles");
const StudyDiseasesInGnomadTable = () => {
    const elementId = 'study-diseases-in-gnomad-table';
    return (react_1.default.createElement("div", null,
        react_1.default.createElement(TableStyles_1.StatsTable, { id: elementId },
            react_1.default.createElement("thead", null,
                react_1.default.createElement(TableStyles_1.StatsTableHeaderRow, null,
                    react_1.default.createElement("th", null, "Phenotypes"),
                    react_1.default.createElement("th", null, "Case"),
                    react_1.default.createElement("th", null, "Control"),
                    react_1.default.createElement("th", null, "Unknown"),
                    react_1.default.createElement("th", null, "Total"),
                    react_1.default.createElement("th", null, "% of cases out of all v4 exomes"))),
            react_1.default.createElement(TableStyles_1.StatsTableBody, null,
                react_1.default.createElement("tr", null,
                    react_1.default.createElement("td", null, "Alzheimer's disease"),
                    react_1.default.createElement("td", null, "2,594"),
                    react_1.default.createElement("td", null, "665"),
                    react_1.default.createElement("td", null, "1,632"),
                    react_1.default.createElement("td", null, "4,890"),
                    react_1.default.createElement("td", null, "0.35%")),
                react_1.default.createElement("tr", null,
                    react_1.default.createElement("td", null, "Atrial Fibrillation"),
                    react_1.default.createElement("td", null, "4,398"),
                    react_1.default.createElement("td", null, "3,546"),
                    react_1.default.createElement("td", null, "38,289"),
                    react_1.default.createElement("td", null, "46,233"),
                    react_1.default.createElement("td", null, "0.60%")),
                react_1.default.createElement("tr", null,
                    react_1.default.createElement("td", null, "Biobank or control dataset*"),
                    react_1.default.createElement("td", null, "-"),
                    react_1.default.createElement("td", null, "24,016"),
                    react_1.default.createElement("td", null, "447,750"),
                    react_1.default.createElement("td", null, "471,766"),
                    react_1.default.createElement("td", null, "N/A")),
                react_1.default.createElement("tr", null,
                    react_1.default.createElement("td", null, "Bipolar disorder"),
                    react_1.default.createElement("td", null, "19,284"),
                    react_1.default.createElement("td", null, "16,383"),
                    react_1.default.createElement("td", null, "80"),
                    react_1.default.createElement("td", null, "35,747"),
                    react_1.default.createElement("td", null, "2.64%")),
                react_1.default.createElement("tr", null,
                    react_1.default.createElement("td", null, "Cardiac arrhythmia"),
                    react_1.default.createElement("td", null, "458"),
                    react_1.default.createElement("td", null, "-"),
                    react_1.default.createElement("td", null, "-"),
                    react_1.default.createElement("td", null, "458"),
                    react_1.default.createElement("td", null, "0.06%")),
                react_1.default.createElement("tr", null,
                    react_1.default.createElement("td", null, "Coronary heart disease"),
                    react_1.default.createElement("td", null, "1,557"),
                    react_1.default.createElement("td", null, "-"),
                    react_1.default.createElement("td", null, "-"),
                    react_1.default.createElement("td", null, "1,557"),
                    react_1.default.createElement("td", null, "0.21%")),
                react_1.default.createElement("tr", null,
                    react_1.default.createElement("td", null, "Inflammatory bowel disease spectrum and related disorders^"),
                    react_1.default.createElement("td", null, "35,008"),
                    react_1.default.createElement("td", null, "11,928"),
                    react_1.default.createElement("td", null, "280"),
                    react_1.default.createElement("td", null, "47,217"),
                    react_1.default.createElement("td", null, "4.79%")),
                react_1.default.createElement("tr", null,
                    react_1.default.createElement("td", null, "Myocardial infarction"),
                    react_1.default.createElement("td", null, "11,900"),
                    react_1.default.createElement("td", null, "369"),
                    react_1.default.createElement("td", null, "-"),
                    react_1.default.createElement("td", null, "12,269"),
                    react_1.default.createElement("td", null, "1.63%")),
                react_1.default.createElement("tr", null,
                    react_1.default.createElement("td", null, "Neurodevelopmental**"),
                    react_1.default.createElement("td", null, "-"),
                    react_1.default.createElement("td", null, "132"),
                    react_1.default.createElement("td", null, "-"),
                    react_1.default.createElement("td", null, "143"),
                    react_1.default.createElement("td", null, "N/A")),
                react_1.default.createElement("tr", null,
                    react_1.default.createElement("td", null, "Non-specific cardiovascular disease"),
                    react_1.default.createElement("td", null, "1,888"),
                    react_1.default.createElement("td", null, "11,376"),
                    react_1.default.createElement("td", null, "15,000"),
                    react_1.default.createElement("td", null, "28,264"),
                    react_1.default.createElement("td", null, "0.26%")),
                react_1.default.createElement("tr", null,
                    react_1.default.createElement("td", null, "Schizophrenia spectrum and related disorders"),
                    react_1.default.createElement("td", null, "30,278"),
                    react_1.default.createElement("td", null, "17,689"),
                    react_1.default.createElement("td", null, "39"),
                    react_1.default.createElement("td", null, "47,994"),
                    react_1.default.createElement("td", null, "4.14%")),
                react_1.default.createElement("tr", null,
                    react_1.default.createElement("td", null, "Type 2 Diabetes"),
                    react_1.default.createElement("td", null, "17,506"),
                    react_1.default.createElement("td", null, "13,096"),
                    react_1.default.createElement("td", null, "3,807"),
                    react_1.default.createElement("td", null, "34,409"),
                    react_1.default.createElement("td", null, "2.39%"))),
            react_1.default.createElement(TableStyles_1.StatsTableFooter, null,
                react_1.default.createElement("tr", null,
                    react_1.default.createElement("td", null, "Grand Total"),
                    react_1.default.createElement("td", null, "124,871"),
                    react_1.default.createElement("td", null, "99,200"),
                    react_1.default.createElement("td", null, "506,877"),
                    react_1.default.createElement("td", null, "730,947"),
                    react_1.default.createElement("td", null, "17.08%"))),
            react_1.default.createElement(TableStyles_1.StatsTableCaption, null,
                react_1.default.createElement("div", null, "* This category includes: GTEx, 1KG, UKBB, and the Qatar Genome Project, as well as the FinnGen and MGB biobank samples when no phenotype was specified"),
                react_1.default.createElement("div", null,
                    ' ',
                    "^ includes diseases like Crohn's disease, irritable bowel syndrome, interstitial cystitis, ulcerative colitis",
                    ' '),
                react_1.default.createElement("div", null, "** Neurodevelopmental controls are unaffected parents of children with confirmed or suspected de novo cause of their neurodevelopmental disorder"))),
        react_1.default.createElement("div", null,
            react_1.default.createElement(DownloadFigure_1.DownloadElementAsPNGButton, { elementId: elementId }))));
};
exports.default = StudyDiseasesInGnomadTable;
//# sourceMappingURL=StudyDiseasesInGnomadTable.js.map