"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const react_1 = __importDefault(require("react"));
const DownloadFigure_1 = require("../DownloadFigure");
const TableStyles_1 = require("./TableStyles");
const V4GeneticAncestryTable = () => {
    const elementId = 'v4-genetic-ancestry-group-size-table';
    return (react_1.default.createElement("div", null,
        react_1.default.createElement(TableStyles_1.StatsTable, { id: elementId },
            react_1.default.createElement("thead", null,
                react_1.default.createElement(TableStyles_1.StatsTableHeaderRow, null,
                    react_1.default.createElement("th", { style: { width: '15%' } }, "Imputed Genetic Ancestry Group for v4"),
                    react_1.default.createElement("th", { style: { width: '15%' } }, "# of individuals"),
                    react_1.default.createElement("th", { style: { width: '20%' } },
                        react_1.default.createElement("span", null, "Study-provided* labels"),
                        react_1.default.createElement("div", { style: { fontSize: '0.65em' } },
                            ' ',
                            "(% of imputed genetic ancestry group with self-reported or research assigned label)")),
                    react_1.default.createElement("th", { style: { width: '50%' } }, `Study-provided* labels that make up <1%`)),
                react_1.default.createElement(TableStyles_1.StatsTableSubHeaderRow, null,
                    react_1.default.createElement("th", null,
                        react_1.default.createElement("i", null, "Genetically Derived")),
                    react_1.default.createElement("th", null,
                        react_1.default.createElement("i", null, "#")),
                    react_1.default.createElement("th", null,
                        react_1.default.createElement("i", null, "Self-reported or researcher assigned")),
                    react_1.default.createElement("th", null,
                        react_1.default.createElement("i", null, "Self-reported or researcher assigned")))),
            react_1.default.createElement(TableStyles_1.StatsTableBody, null,
                react_1.default.createElement("tr", null,
                    react_1.default.createElement("td", null, "Admixed American (AMR)"),
                    react_1.default.createElement("td", null, "30,019"),
                    react_1.default.createElement("td", null,
                        react_1.default.createElement("div", null, "Mexican (24.70%)"),
                        react_1.default.createElement("div", null, "Costa Rican (8.54%)"),
                        react_1.default.createElement("div", null, "Latino (8.52%)"),
                        react_1.default.createElement("br", null),
                        react_1.default.createElement("div", null, "No label provided (53.86%)")),
                    react_1.default.createElement("td", null, "Black, British, Colombian, Do not Know, Dutch, Finnish, French Canadian, Hawaiian, Indigenous American, Karitiana, Maya, Mexican-American, Mixed, Other, Other Mixed, Other white, Peruvian, Pima, Prefer not to answer, Puerto Rican, Rapa Nui from Easter Island, Surui, White, White and Asian, White and Black Caribbean")),
                react_1.default.createElement("tr", null,
                    react_1.default.createElement("td", null, "African/African American (AFR)"),
                    react_1.default.createElement("td", null, "37,545"),
                    react_1.default.createElement("td", null,
                        react_1.default.createElement("div", null, "Caribbean (9.49%)"),
                        react_1.default.createElement("div", null, "African (7.36%)"),
                        react_1.default.createElement("div", null, "Other (1.97%)"),
                        react_1.default.createElement("div", null, "Black (1.66%)"),
                        react_1.default.createElement("br", null),
                        react_1.default.createElement("div", null, "No label provided (75.06%)")),
                    react_1.default.createElement("td", null, "African / Pygmy, African American, African Caribbean, African-American, Asian, Bantu Kenya, Bantu S Africa, Biaka Pygmy, Black or Black British, British, Costa Rican, Do not Know, Esan, Finnish, French Canadian, Gambian, Indigenous American, Latino, Luhya, Mandenka, Mbuti Pygmy, Mende, Mexican, Mixed, Mozabite, Other Asian, Other Black, Other Mixed, Prefer not to answer, Puerto Rican, Qatari, San, South Asian, Sub-Saharan African, White, White and Asian, White and Black African, White and Black Caribbean, Yoruba")),
                react_1.default.createElement("tr", null,
                    react_1.default.createElement("td", null, "Amish (AMI)"),
                    react_1.default.createElement("td", null, "456"),
                    react_1.default.createElement("td", null,
                        react_1.default.createElement("p", null, "No label provided (100.00%)")),
                    react_1.default.createElement("td", null, "-")),
                react_1.default.createElement("tr", null,
                    react_1.default.createElement("td", null, "Ashkenazi Jewish (ASJ)"),
                    react_1.default.createElement("td", null, "14,804"),
                    react_1.default.createElement("td", null,
                        react_1.default.createElement("div", null, "British (10.23%)"),
                        react_1.default.createElement("div", null, "Other white (5.57%)"),
                        react_1.default.createElement("div", null, "White (4.67%)"),
                        react_1.default.createElement("div", null, "Other (1.28%)"),
                        react_1.default.createElement("br", null),
                        react_1.default.createElement("div", null, "No label provided (77.63%)")),
                    react_1.default.createElement("td", null, "Asian, Costa Rican, Do not Know, Dutch, Finnish, French Canadian, Irish, Not Hispanic or Latino, Other Mixed, Prefer not to answer")),
                react_1.default.createElement("tr", null,
                    react_1.default.createElement("td", null, "East Asian (EAS)"),
                    react_1.default.createElement("td", null, "22,448"),
                    react_1.default.createElement("td", null,
                        react_1.default.createElement("div", null, "Japanese (19.99%)"),
                        react_1.default.createElement("div", null, "Chinese (5.90%)"),
                        react_1.default.createElement("div", null, "Other (1.43%)"),
                        react_1.default.createElement("div", null, "Asian (1.35%)"),
                        react_1.default.createElement("br", null),
                        react_1.default.createElement("div", null, "No label provided (67.94%)")),
                    react_1.default.createElement("td", null, "Asian or Asian British, British, Cambodian, Chinese Dai, Costa Rican, Dai, Daur, Do not Know, Finnish, French Canadian, Han, Han Chinese, Hezhen, Indigenous American, Kinh, Lahu, Miaozu, Mixed, Mongola, Naxi, Oroqen, Other Asian, Other Mixed, Prefer not to answer, She, Southern Han Chinese, Tu, Tujia, Uygur, White, White and Asian, Xibo, Yakut, Yizu")),
                react_1.default.createElement("tr", null,
                    react_1.default.createElement("td", null, "Finnish (FIN)"),
                    react_1.default.createElement("td", null, "32,026"),
                    react_1.default.createElement("td", null,
                        react_1.default.createElement("div", null, "Finnish (81.20%)"),
                        react_1.default.createElement("br", null),
                        react_1.default.createElement("div", null, "No label provided (18.31%)")),
                    react_1.default.createElement("td", null, "British, Estonian, Other, Other white, Swedish, White")),
                react_1.default.createElement("tr", null,
                    react_1.default.createElement("td", null, "Middle Eastern (MID)"),
                    react_1.default.createElement("td", null, "3,031"),
                    react_1.default.createElement("td", null,
                        react_1.default.createElement("div", null, "Other (16.07%)"),
                        react_1.default.createElement("div", null, "Bedouin (13.89%)"),
                        react_1.default.createElement("div", null, "Arab (5.386%)"),
                        react_1.default.createElement("div", null, "Persian (4.55%)"),
                        react_1.default.createElement("div", null, "Other white (4.06%)"),
                        react_1.default.createElement("div", null, "Other Asian (3.73%)"),
                        react_1.default.createElement("div", null, "Qatari (2.94%)"),
                        react_1.default.createElement("div", null, "White (2.73%)"),
                        react_1.default.createElement("div", null, "Palestinian (1.09%)"),
                        react_1.default.createElement("div", null, "French Canadian (1.06%)"),
                        react_1.default.createElement("br", null),
                        react_1.default.createElement("div", null, "No label provided (38.677%)")),
                    react_1.default.createElement("td", null, "Asian, Asian or Asian British, British, Do not Know, Druze, Dutch, European, Finnish, German, Indian, Mixed, Mozabite, Other Mixed, Pakistani, Prefer not to answer, South Asian, Sub-Saharan African, White and Asian, White and Black African")),
                react_1.default.createElement("tr", null,
                    react_1.default.createElement("td", null, "Non-Finnish European (NFE)"),
                    react_1.default.createElement("td", null, "590,031"),
                    react_1.default.createElement("td", null,
                        react_1.default.createElement("div", null, "British (60.63%)"),
                        react_1.default.createElement("div", null, "Other white (2.02%)"),
                        react_1.default.createElement("div", null, "White (1.871%)"),
                        react_1.default.createElement("div", null, "Irish (1.50%)"),
                        react_1.default.createElement("br", null),
                        react_1.default.createElement("div", null, "No label provided (32.40%)")),
                    react_1.default.createElement("td", null, "Adygei, American Indian, Asian or Asian British, Basque, Black, Black or Black British, Chinese, Costa Rican, Do not Know, Dutch, English, English_Scottish, Estonian, European, Finnish, French, French Acadian, French Acadian_French Quebecois, French Acadian_Scottish, French Canadian, German, German_Irish, German/English_Scottish, Iberian, Indian, Indigenous American, Irish_French Acadian, Irish_French Quebecois, Irish_Scottish, Italian, Latino, Mexican, Mixed, Native Hawaiian, Not Hispanic or Latino, Orcadian, Other, Other Asian, Other Mixed, Persian, Prefer not to answer, Qatari, Russian, Sardinian, Scottish, Scottish_English, Scottish_European French, Scottish_German, Scottish_Irish, Swedish, Toscani, Utah Residents (European Ancestry), White and Asian, White and Black African, White and Black Caribbean")),
                react_1.default.createElement("tr", null,
                    react_1.default.createElement("td", null, "Remaining Individuals (RMI)"),
                    react_1.default.createElement("td", null, "31,256"),
                    react_1.default.createElement("td", null,
                        react_1.default.createElement("div", null, "British (21.79%)"),
                        react_1.default.createElement("div", null, "Irish (6.45%)"),
                        react_1.default.createElement("div", null, "Other (3.33%)"),
                        react_1.default.createElement("div", null, "Other white (3.23%)"),
                        react_1.default.createElement("div", null, "White (3.13%)"),
                        react_1.default.createElement("div", null, "Finnish (2.61%)"),
                        react_1.default.createElement("div", null, "White and Asian (1.91%)"),
                        react_1.default.createElement("div", null, "Other Mixed (1.61%)"),
                        react_1.default.createElement("div", null, "Other Asian (1.38%)"),
                        react_1.default.createElement("br", null),
                        react_1.default.createElement("div", null, "No label provided (48.26%)")),
                    react_1.default.createElement("td", null, "African, African American, African-American, Asian, Asian or Asian British, Bangladeshi, Bedouin, Black, Black or Black British, Cambodian, Caribbean, Chinese, Colombian, Costa Rican, Do not Know, Druze, Dutch, Estonian, French Canadian, Hazara, Hispanic, Indian, Indigenous American, Japanese, Latino, Melanesian, Mexican, Mixed, Mozabite, Native Hawaiian, Not Hispanic or Latino, Other Black, Pakistani, Palestinian, Papuan, Persian, Prefer not to answer, Puerto Rican, Qatari, South Asian, Sub-Saharan African, Uygur, White and Black African, White and Black Caribbean, Yakut")),
                react_1.default.createElement("tr", null,
                    react_1.default.createElement("td", null, "South Asian (SAS)"),
                    react_1.default.createElement("td", null, "45,546"),
                    react_1.default.createElement("td", null,
                        react_1.default.createElement("div", null, "South Asian (61.38%)"),
                        react_1.default.createElement("div", null, "Indian (10.63%)"),
                        react_1.default.createElement("div", null, "Pakistani (5.79%)"),
                        react_1.default.createElement("div", null, "Other Asian (1.97%)"),
                        react_1.default.createElement("br", null),
                        react_1.default.createElement("div", null, "No label provided (16.47%)")),
                    react_1.default.createElement("td", null, "African, Asian, Asian or Asian British, Balochi, Bangladeshi, Bengali, Black, Brahui, British, Burusho, Caribbean, Chinese, Do not Know, Dutch, Finnish, French Canadian, Gujarati, Hazara, Indian Telugu, Kalash, Makrani, Mixed, Other, Other Black, Other Mixed, Other white, Pathan, Prefer not to answer, Punjabi, Qatari, Sindhi, Sri Lankan Tamil, Uygur, White, White and Asian, White and Black Caribbean"))),
            react_1.default.createElement(TableStyles_1.StatsTableCaption, null,
                react_1.default.createElement("div", null, "*Study-provided labels are the descriptions given to the gnomAD team in the accompanying metadata. These labels can sometime be assigned at the study-level, others are provided at the individual level."),
                react_1.default.createElement("br", null),
                react_1.default.createElement("div", null, "These labels are also a mix of researcher assigned, sometimes participant self reported. None of these labels are used for training our imputed ancestry data."))),
        react_1.default.createElement("div", null,
            react_1.default.createElement(DownloadFigure_1.DownloadElementAsPNGButton, { elementId: elementId }))));
};
exports.default = V4GeneticAncestryTable;
//# sourceMappingURL=V4GeneticAncestryTable.js.map